# Site settings
encoding: utf-8
title: Simplism Developer
email: simplismdeveloper@gmail.com
description: 단순한 코드 템플릿 혹은 각종 팁을 보기쉽게 정리하여, 무료 오픈소스로 배포하는 사이트
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://simplismdeveloper.github.io" # the base hostname & protocol for your site
author: Seoklae, Kim
github_username:  simplismdeveloper
github_repo: simplismdeveloper.github.io

# Build settings
highlighters: pygments
markdown: kramdown
